// WordCraft content. Add a word = add one line: { word, emoji }.
// Words are always taught/displayed in UPPERCASE.
const ZONES = [
  {
    id: "meadow",
    name: "Starter Meadow",
    icon: "🌈",
    boss: { name: "Campfire Buddy", img: "assets/brainrots/campfire_dog.png" },
    words: [
      { word: "cat", emoji: "🐱" },
      { word: "dog", emoji: "🐶" },
      { word: "bird", emoji: "🐦" },
      { word: "fish", emoji: "🐟" },
      { word: "apple", emoji: "🍎" },
      { word: "sun", emoji: "☀️" },
      { word: "red", emoji: "🔴" },
      { word: "blue", emoji: "🔵" },
      { word: "green", emoji: "🟢" },
      { word: "one", emoji: "1️⃣" },
      { word: "two", emoji: "2️⃣" },
      { word: "three", emoji: "3️⃣" },
    ],
  },
  {
    id: "biome",
    name: "Blocky Biome",
    icon: "⛏️",
    boss: { name: "Steve", img: "assets/brainrots/minecraft_steve.png" },
    words: [
      { word: "diamond", emoji: "💎" },
      { word: "sword", emoji: "🗡️" },
      { word: "tree", emoji: "🌳" },
      { word: "house", emoji: "🏠" },
      { word: "stone", emoji: "🪨" },
      { word: "wolf", emoji: "🐺" },
      { word: "cake", emoji: "🎂" },
      { word: "bed", emoji: "🛏️" },
      { word: "door", emoji: "🚪" },
      { word: "fire", emoji: "🔥" },
      { word: "egg", emoji: "🥚" },
      { word: "gold", emoji: "🪙" },
    ],
  },
  {
    id: "stadium",
    name: "Super Stadium",
    icon: "⚽",
    boss: { name: "Blocky Miner", img: "assets/brainrots/roblox_miner.png" },
    words: [
      { word: "ball", emoji: "⚽" },
      { word: "goal", emoji: "🥅" },
      { word: "shoe", emoji: "👟" },
      { word: "cup", emoji: "🏆" },
      { word: "flag", emoji: "🚩" },
      { word: "run", emoji: "🏃" },
      { word: "kick", emoji: "🦵" },
      { word: "star", emoji: "⭐" },
      { word: "fast", emoji: "⚡" },
      { word: "king", emoji: "👑" },
      { word: "hand", emoji: "✋" },
      { word: "win", emoji: "🥇" },
    ],
  },
  {
    id: "ocean",
    name: "Ocean World",
    icon: "🌊",
    boss: { name: "Splash", img: "assets/brainrots/water_drop.png" },
    words: [
      { word: "shark", emoji: "🦈" },
      { word: "whale", emoji: "🐋" },
      { word: "crab", emoji: "🦀" },
      { word: "boat", emoji: "⛵" },
      { word: "wave", emoji: "🌊" },
      { word: "shell", emoji: "🐚" },
      { word: "turtle", emoji: "🐢" },
      { word: "dolphin", emoji: "🐬" },
      { word: "squid", emoji: "🦑" },
      { word: "swim", emoji: "🏊" },
      { word: "sand", emoji: "🏖️" },
      { word: "dive", emoji: "🤿" },
    ],
  },
  {
    id: "arcade",
    name: "Neon Arcade",
    icon: "🕹️",
    boss: { name: "Gameboy Buddy", img: "assets/brainrots/gameboy_buddy.png" },
    words: [
      { word: "jump", emoji: "🦘" },
      { word: "play", emoji: "🎮" },
      { word: "robot", emoji: "🤖" },
      { word: "car", emoji: "🚗" },
      { word: "rocket", emoji: "🚀" },
      { word: "pizza", emoji: "🍕" },
      { word: "music", emoji: "🎵" },
      { word: "happy", emoji: "😀" },
      { word: "dance", emoji: "💃" },
      { word: "magic", emoji: "🪄" },
      { word: "ghost", emoji: "👻" },
      { word: "candy", emoji: "🍬" },
    ],
  },
  {
    // the meme characters are combos of real nouns — this zone teaches the ingredients
    id: "brainrot",
    name: "Brainrot Land",
    icon: "🧠",
    boss: { name: "Troll Face", img: "assets/brainrots/troll_face.png" },
    words: [
      { word: "banana", emoji: "🍌" },
      { word: "monkey", emoji: "🐵" },
      { word: "plane", emoji: "✈️" },
      { word: "coffee", emoji: "☕" },
      { word: "drum", emoji: "🥁" },
      { word: "frog", emoji: "🐸" },
      { word: "wheel", emoji: "🛞" },
      { word: "cow", emoji: "🐮" },
      { word: "planet", emoji: "🪐" },
      { word: "elephant", emoji: "🐘" },
      { word: "cactus", emoji: "🌵" },
      { word: "camel", emoji: "🐫" },
    ],
  },
];

// Brainrot collection: bosses (in ZONES above) are stolen by beating them;
// these are bought with coins. Prices follow rarity, like in Steal a Brainrot.
const BRAINROTS = [
  { id: "sushi", name: "Sushi Pal", img: "assets/brainrots/sushi_dumpling.png", price: 30 },
  { id: "toiletpaper", name: "TP Twins", img: "assets/brainrots/toilet_paper_twins.png", price: 35 },
  { id: "shibadoge", name: "Much Brain Doggo", img: "assets/brainrots/much_brain_doggo.png", price: 45 },
  { id: "mushroomcat", name: "Mushroom Cat", img: "assets/brainrots/rainbow_mushroom_cat.png", price: 55 },
  { id: "avocado", name: "Sad Avocado", img: "assets/brainrots/sad_avocado.png", price: 60 },
  { id: "amongus", name: "Sus Red", img: "assets/brainrots/among_us_red.png", price: 70 },
  { id: "purpleblob", name: "Purple Blob", img: "assets/brainrots/purple_blob.png", price: 75 },
  { id: "spaghetticat", name: "Spaghetti Cat", img: "assets/brainrots/spaghetti_cat.png", price: 80 },
  { id: "boba", name: "Boba Buddy", img: "assets/brainrots/boba_tea.png", price: 90 },
  { id: "campfiredog", name: "Campfire Dog", img: "assets/brainrots/campfire_dog.png", price: 40 },
  { id: "rainbowjelly", name: "Rainbow Jelly", img: "assets/brainrots/rainbow_jelly.png", price: 50 },
  { id: "wingedcat", name: "Winged Cat", img: "assets/brainrots/winged_cat.png", price: 100 },
  { id: "letterb", name: "Letter B", img: "assets/brainrots/letter_b_eyes.png", price: 25 },
  { id: "mushroomfam", name: "Mushroom Family", img: "assets/brainrots/mushroom_family.png", price: 65 },
  { id: "frankenstein", name: "Frankie", img: "assets/brainrots/frankenstein.png", price: 110 },
  { id: "binaryghost", name: "Binary Ghost", img: "assets/brainrots/binary_ghost.png", price: 120 },
  { id: "oneeyealien", name: "One-Eye Alien", img: "assets/brainrots/one_eye_alien.png", price: 95 },
  { id: "cassettebot", name: "Cassette Bot", img: "assets/brainrots/cassette_bot.png", price: 130 },
  { id: "lightbulb", name: "Bright Idea", img: "assets/brainrots/lightbulb_head.png", price: 140 },
  { id: "hearteye", name: "Heart Eye Blob", img: "assets/brainrots/heart_eye_blob.png", price: 85 },
  { id: "worm", name: "Wiggly Worm", img: "assets/brainrots/green_worm.png", price: 35 },
  { id: "bluebear", name: "Blue Bear", img: "assets/brainrots/blue_bear.png", price: 105 },
  { id: "manyeyedmouth", name: "Big Mouth", img: "assets/brainrots/many_eyed_mouth.png", price: 150 },
  { id: "lettera", name: "Letter A", img: "assets/brainrots/letter_a.png", price: 25 },
  { id: "trollpanda", name: "Troll Panda", img: "assets/brainrots/troll_panda.png", price: 160 },
  { id: "manyeyedblue", name: "Spooky Blue", img: "assets/brainrots/many_eyed_blue.png", price: 170 },
  { id: "foureyedcat", name: "Four-Eyed Cat", img: "assets/brainrots/four_eyed_cat.png", price: 115 },
  { id: "reddevil", name: "Little Devil", img: "assets/brainrots/red_devil.png", price: 125 },
  { id: "applecore", name: "Apple Core", img: "assets/brainrots/apple_core.png", price: 45 },
  { id: "greenalien", name: "Green Alien", img: "assets/brainrots/green_alien.png", price: 135 },
  { id: "springrobot", name: "Spring Robot", img: "assets/brainrots/spring_robot.png", price: 145 },
];

// Shop gear: slot is where it renders on the avatar.
const GEAR = [
  { id: "cap", emoji: "🧢", slot: "hat", price: 20 },
  { id: "crown", emoji: "👑", slot: "hat", price: 60 },
  { id: "helmet", emoji: "⛑️", slot: "hat", price: 40 },
  { id: "tophat", emoji: "🎩", slot: "hat", price: 50 },
  { id: "shades", emoji: "🕶️", slot: "eyes", price: 30 },
  { id: "goggles", emoji: "🥽", slot: "eyes", price: 25 },
  { id: "sword", emoji: "🗡️", slot: "hand", price: 45 },
  { id: "ball", emoji: "⚽", slot: "hand", price: 35 },
  { id: "guitar", emoji: "🎸", slot: "hand", price: 55 },
  { id: "wand", emoji: "🪄", slot: "hand", price: 70 },
];
