// WordCraft content. Add a word = add one line: { word, emoji }.
// Words are always taught/displayed in UPPERCASE.
const ZONES = [
  {
    id: "meadow",
    name: "Starter Meadow",
    icon: "🌈",
    boss: { name: "Sleepy Bear", emoji: "🐻" },
    words: [
      { word: "cat", emoji: "🐱" },
      { word: "dog", emoji: "🐶" },
      { word: "bird", emoji: "🐦" },
      { word: "fish", emoji: "🐟" },
      { word: "apple", emoji: "🍎" },
      { word: "sun", emoji: "☀️" },
      { word: "red", emoji: "🔴" },
      { word: "blue", emoji: "🔵" },
      { word: "green", emoji: "🟢" },
      { word: "one", emoji: "1️⃣" },
      { word: "two", emoji: "2️⃣" },
      { word: "three", emoji: "3️⃣" },
    ],
  },
  {
    id: "biome",
    name: "Blocky Biome",
    icon: "⛏️",
    boss: { name: "Cave Dragon", emoji: "🐲" },
    words: [
      { word: "diamond", emoji: "💎" },
      { word: "sword", emoji: "🗡️" },
      { word: "tree", emoji: "🌳" },
      { word: "house", emoji: "🏠" },
      { word: "stone", emoji: "🪨" },
      { word: "wolf", emoji: "🐺" },
      { word: "cake", emoji: "🎂" },
      { word: "bed", emoji: "🛏️" },
      { word: "door", emoji: "🚪" },
      { word: "fire", emoji: "🔥" },
      { word: "egg", emoji: "🥚" },
      { word: "gold", emoji: "🪙" },
    ],
  },
  {
    id: "stadium",
    name: "Super Stadium",
    icon: "⚽",
    boss: { name: "Goal Giant", emoji: "🦁" },
    words: [
      { word: "ball", emoji: "⚽" },
      { word: "goal", emoji: "🥅" },
      { word: "shoe", emoji: "👟" },
      { word: "cup", emoji: "🏆" },
      { word: "flag", emoji: "🚩" },
      { word: "run", emoji: "🏃" },
      { word: "kick", emoji: "🦵" },
      { word: "star", emoji: "⭐" },
      { word: "fast", emoji: "⚡" },
      { word: "king", emoji: "👑" },
      { word: "hand", emoji: "✋" },
      { word: "win", emoji: "🥇" },
    ],
  },
  {
    id: "arcade",
    name: "Neon Arcade",
    icon: "🕹️",
    boss: { name: "Mega Robot", emoji: "🤖" },
    words: [
      { word: "jump", emoji: "🦘" },
      { word: "play", emoji: "🎮" },
      { word: "robot", emoji: "🤖" },
      { word: "car", emoji: "🚗" },
      { word: "rocket", emoji: "🚀" },
      { word: "pizza", emoji: "🍕" },
      { word: "music", emoji: "🎵" },
      { word: "happy", emoji: "😀" },
      { word: "dance", emoji: "💃" },
      { word: "magic", emoji: "🪄" },
      { word: "ghost", emoji: "👻" },
      { word: "candy", emoji: "🍬" },
    ],
  },
];

// Shop gear: slot is where it renders on the avatar.
const GEAR = [
  { id: "cap", emoji: "🧢", slot: "hat", price: 20 },
  { id: "crown", emoji: "👑", slot: "hat", price: 60 },
  { id: "helmet", emoji: "⛑️", slot: "hat", price: 40 },
  { id: "tophat", emoji: "🎩", slot: "hat", price: 50 },
  { id: "shades", emoji: "🕶️", slot: "eyes", price: 30 },
  { id: "goggles", emoji: "🥽", slot: "eyes", price: 25 },
  { id: "sword", emoji: "🗡️", slot: "hand", price: 45 },
  { id: "ball", emoji: "⚽", slot: "hand", price: 35 },
  { id: "guitar", emoji: "🎸", slot: "hand", price: 55 },
  { id: "wand", emoji: "🪄", slot: "hand", price: 70 },
];
